//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarDealership.bd
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompletedWork
    {
        public int idCompleted { get; set; }
        public Nullable<int> id_Order { get; set; }
        public Nullable<int> id_Price { get; set; }
        public Nullable<System.DateTime> DateComplite { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Price Price { get; set; }
    }
}
