//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarDealership.bd
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartsWarehouse
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PartsWarehouse()
        {
            this.UnderRepairs = new HashSet<UnderRepair>();
        }
    
        public int idPart { get; set; }
        public string NamePart { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<int> id_Supplier { get; set; }
    
        public virtual Supplier Supplier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UnderRepair> UnderRepairs { get; set; }
    }
}
